import {
  PERIODIC, DAILY, WEEKLY, MONTHLY, QUARTERLY, YEARLY,
  DAILY_REG, WEEKLY_REG, MONTHLY_REG, QUARTERLY_REG, YEARLY_REG
} from './periodic'
import { PARA, PROJECT, SUB_AREA, AREA, RESOURCE, ARCHIVE } from './para';




const TAG = 'Tag';
const FOLDER = 'Folder';
const INDEX = 'Index';

const ERROR_MESSAGE = 'ERROR_MESSAGE';
const MESSAGE = 'MESSAGE';

const PLUGIN_NAME = "PLUGIN_NAME"

export {
  // Periodic Constants
  PERIODIC, DAILY, WEEKLY, MONTHLY, QUARTERLY, YEARLY,
  DAILY_REG, WEEKLY_REG, MONTHLY_REG, QUARTERLY_REG, YEARLY_REG,
  // PARA Constants
  PARA, PROJECT, SUB_AREA, AREA, RESOURCE, ARCHIVE,
  // General Constants
  ERROR_MESSAGE, MESSAGE, TAG, FOLDER, INDEX, PLUGIN_NAME,
}
